/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as WorkflowsWorkflowIdIndexRouteImport } from './routes/workflows/$workflowId/index'
import { Route as WorkflowsWorkflowIdRunsRunIdRouteImport } from './routes/workflows/$workflowId/runs/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdIndexRoute =
  WorkflowsWorkflowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkflowsWorkflowIdRoute,
  } as any)
const WorkflowsWorkflowIdRunsRunIdRoute =
  WorkflowsWorkflowIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => WorkflowsWorkflowIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/workflows/$workflowId/': typeof WorkflowsWorkflowIdIndexRoute
  '/workflows/$workflowId/runs/$runId': typeof WorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdIndexRoute
  '/workflows/$workflowId/runs/$runId': typeof WorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/workflows/$workflowId/': typeof WorkflowsWorkflowIdIndexRoute
  '/workflows/$workflowId/runs/$runId': typeof WorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workflows/$workflowId'
    | '/workflows/$workflowId/'
    | '/workflows/$workflowId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workflows/$workflowId' | '/workflows/$workflowId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/workflows/$workflowId'
    | '/workflows/$workflowId/'
    | '/workflows/$workflowId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId/': {
      id: '/workflows/$workflowId/'
      path: '/'
      fullPath: '/workflows/$workflowId/'
      preLoaderRoute: typeof WorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof WorkflowsWorkflowIdRoute
    }
    '/workflows/$workflowId/runs/$runId': {
      id: '/workflows/$workflowId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/workflows/$workflowId/runs/$runId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRunsRunIdRouteImport
      parentRoute: typeof WorkflowsWorkflowIdRoute
    }
  }
}

interface WorkflowsWorkflowIdRouteChildren {
  WorkflowsWorkflowIdIndexRoute: typeof WorkflowsWorkflowIdIndexRoute
  WorkflowsWorkflowIdRunsRunIdRoute: typeof WorkflowsWorkflowIdRunsRunIdRoute
}

const WorkflowsWorkflowIdRouteChildren: WorkflowsWorkflowIdRouteChildren = {
  WorkflowsWorkflowIdIndexRoute: WorkflowsWorkflowIdIndexRoute,
  WorkflowsWorkflowIdRunsRunIdRoute: WorkflowsWorkflowIdRunsRunIdRoute,
}

const WorkflowsWorkflowIdRouteWithChildren =
  WorkflowsWorkflowIdRoute._addFileChildren(WorkflowsWorkflowIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
