version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
    groups:
      commitlint:
        patterns:
          - "*commitlint*"
      eslint:
        patterns:
          - "@eslint/js"
          - "eslint"
      react:
        patterns:
          - "@types/react"
          - "@types/react-dom"
          - "react"
          - "react-dom"
      tanstack:
        patterns:
          - "*tanstack*"
      tailwind:
        patterns:
          - "*tailwind*"
      vitest:
        patterns:
          - "*vitest*"
    open-pull-requests-limit: 20
